//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampbellSupply.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public System.Guid ShippingAddressId { get; set; }
        public System.Guid BillingAddressId { get; set; }
        public Nullable<System.Guid> CouponId { get; set; }
        public string Number { get; set; }
        public string PaymentTransactionId { get; set; }
        public string PaymentExpiration { get; set; }
        public int PaymentLast4 { get; set; }
        public string PaymentResponse { get; set; }
        public decimal SubTotal { get; set; }
        public decimal ShippingTotal { get; set; }
        public decimal SalesTax { get; set; }
        public bool IsPaid { get; set; }
        public bool IsProcessed { get; set; }
        public bool IsShipped { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Coupon Coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
