//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampbellSupply.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageContent
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Location { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateActiveChanged { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
