//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampbellSupply.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.ProductViewHistories = new HashSet<ProductViewHistory>();
            this.RatedRevieweds = new HashSet<RatedReviewed>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public System.Guid Id { get; set; }
        public int OldId { get; set; }
        public Nullable<System.Guid> ManufacturerId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> SubCategoryId { get; set; }
        public string ManufacturerUPC { get; set; }
        public string Sku { get; set; }
        public string Name { get; set; }
        public string DescriptionShort { get; set; }
        public string DescriptionLong { get; set; }
        public string PartNumber { get; set; }
        public string WebPartNumber { get; set; }
        public string Unknown { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Brand { get; set; }
        public string ImageURL { get; set; }
        public string Status { get; set; }
        public string Market { get; set; }
        public string Group { get; set; }
        public string Mirror { get; set; }
        public string EditedBy { get; set; }
        public decimal Weight { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal OverridePrice { get; set; }
        public decimal SalePrice { get; set; }
        public decimal ShippingPrice { get; set; }
        public int vsibilityID { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsOnSale { get; set; }
        public bool IsShippingValid { get; set; }
        public bool IsTaxable { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateOn { get; set; }
        public Nullable<System.DateTime> DateOff { get; set; }
        public System.DateTime DateActiveChanged { get; set; }
        public System.DateTime DateDeletedChanged { get; set; }
        public System.DateTime DateEdited { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductViewHistory> ProductViewHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatedReviewed> RatedRevieweds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
