//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampbellSupply.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string SessionId { get; set; }
        public System.Guid ProductId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
    }
}
