//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampbellSupply.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyAd
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string ImageName { get; set; }
        public string ImageStoragePath { get; set; }
        public int ImageSizeInBytes { get; set; }
        public int ImageStorageType { get; set; }
        public string FileName { get; set; }
        public string FileStoragePath { get; set; }
        public int FileSizeInBytes { get; set; }
        public int FileStorageType { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
